### PR TITLE
Support opencv4

### PR DESCRIPTION
**Pull request by wyg1997**
The header files of opencv4 is `/usr/include/opencv4/opencv2/*`.
So I run `ln -s opencv4/opencv2 opencv2` before compiling.

### CODE REVIEW

**Comment by lucasjinreal** [comment]
thanks for contributing. Just for confirmation, does:

```c++
#include <opencv/...h>
```
path works with default opencv4 installation ?
Or could be:

```c++
#include <opencv4/opencv2/*.h>
```
?

**Comment by wyg1997** [comment]
> thanks for contributing. Just for confirmation, does:
> 
> ```c++
> #include <opencv/...h>
> ```
> 
> path works with default opencv4 installation ?
> Or could be:
> 
> ```c++
> #include <opencv4/opencv2/*.h>
> ```
> 
> ?

It should be
```c++
#include <opencv4/opencv2/*.h>
```
with default.

So I think adding a header path `${include_dir}/opencv4` will be better.

**Comment by lucasjinreal** [comment]
I think changes include into:

```c++
#include <opencv4/opencv2/*.h>
```
could be more straightforward. Would u like edit these headers and send me an PR for this fix?
Literally we need change these headers:
```
slam.h
vis.h
structures.h
math.h
```
These module were mostly used parts and related to opencv.

**Comment by wyg1997** [comment]
It is my fault. QAQ

I need not to run `ln -s opencv4/opencv2 opencv2`, because opencv header path has been written in `opencv4.pc`. So I just include that path in `CMakeLists.txt`(see commit [f00a5ac](https://github.com/jinfagang/thor/pull/2/commits/f00a5ac7ffeee69d47f8e176dbcbd6bac5bfe56b)).

**Comment by wyg1997** [comment]
> It is my fault. QAQ
> 
> I need not to run `ln -s opencv4/opencv2 opencv2`, because opencv header path has been written in `opencv4.pc`. So I just include that path in `CMakeLists.txt`(see commit [f00a5ac](https://github.com/jinfagang/thor/pull/2/commits/f00a5ac7ffeee69d47f8e176dbcbd6bac5bfe56b)).

I think it is not appropriate to use `#include<opencv4/opencv2/opencv.hpp>` according to [offical example codes](https://github.com/opencv/opencv/blob/master/samples/cpp/drawing.cpp).

**Comment by lucasjinreal** [comment]
OK, including specific in CMakeLists could be better when detects users using opencv4. 'll merges this.

**Pull request merged**
